CREATE TABLE IF NOT EXISTS `cot_reviews` (
	rw_id INT NOT NULL AUTO_INCREMENT,
	rw_page INT NOT NULL,
	rw_user INT NOT NULL,
	rw_username VARCHAR(128) NOT NULL DEFAULT '',
	rw_userip VARCHAR(15) NOT NULL DEFAULT '',
	rw_date INT NOT NULL,
	rw_recommend TINYINT DEFAULT NULL,
	rw_text TEXT NOT NULL,
	rw_pros VARCHAR(255) NOT NULL,
	rw_cons VARCHAR(255) NOT NULL,
	rw_price DECIMAL(12,2) NOT NULL DEFAULT 0,
	rw_rating TINYINT NOT NULL DEFAULT 0,
	rw_rate1 TINYINT,
	rw_rate2 TINYINT,
	rw_rate3 TINYINT,
	rw_rate4 TINYINT,
	rw_rate5 TINYINT,
	rw_rate6 TINYINT,
	rw_rate7 TINYINT,
	rw_rate8 TINYINT,
	rw_rate9 TINYINT,
	rw_rateavg DECIMAL(5,3),
	rw_extra1 VARCHAR(128),
	rw_extra2 VARCHAR(128),
	rw_extra3 VARCHAR(128),
	rw_extra4 VARCHAR(128),
	rw_extra5 VARCHAR(128),
	PRIMARY KEY(rw_id),
	KEY(rw_page),
	KEY(rw_user)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;